[project]
name = "playground-jq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Morten Hansen", email = "morten@winterop.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
playground-jq = "playground_jq:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
